CFLAGS :=-g -O2 -Wall -Wextra -Werror -Wfatal-errors -std=c99 -pedantic
CFLAGS += -I../include -I../lib

CCFLAGS := $(CFLAGS)

OBJS := fiboHeap.c main.c naiveHeap.c node.c

TARGET  := fib 

.PHONY: all clean

include ../GNU_makefile_template
