CCFLAGS = -W -Wall -I.. #-lm
# executable files for this directory
OBJECTS = sort.exe sort2.exe sort3.exe factoring.exe proxy.exe reverse.exe \
	  keyBoard.exe primeFactor.exe divideInteger.exe sphere.exe buildTree.exe \
	  buildTree2.exe 2012.exe minStamp.exe sum532.exe rootNk.exe rootNkNew.exe \
	  mutiply.exe date.exe perfectAndExcessNum.exe permut.exe maxSubSum.exe \
	  minCost.exe factorial.exe moveTree.exe students.exe bigDataRadixConvert.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
