# CFLAGS for users
#
#CCFLAGS = -W -Wall -I../../include
CCFLAGS = -I../../include
LOCFLAGS =
LDFLAGS = -lm

# For each one source file will generate one excutable xx.exe, you can 
# define multiple target.exe in TARGETEXE
TARGETEXE = 
# If sourcefile is c++ type, pls set USECPP=1
USECPP =
# For each target may need more than one source file, define TARGET 
# instead and add linking objects at OBJS
TARGET = rbtree 
OBJS += rbtree.o que.o main.o 

# general makefile template
include ../../GNU_makefile_template
