CCFLAGS = -W -Wall -I.. #-lm
# executable files for this directory
OBJECTS = stringMatch.exe quadEquation.exe wertyu.exe simpleSorting.exe oldBill.exe \
	  fib.exe reverseNum.exe chess.exe chess2.exe sumOfFactorials.exe printPath.exe \
	  printPath2.exe bigInteger.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
