# CFLAGS for users
#
CCFLAGS = -W -Wall -I../include
LOCFLAGS =
LDFLAGS = -lpthread

# For each one source file will generate one excutable xx.exe, you can 
# define multiple target.exe in TARGETEXE
TARGETEXE = 
# If sourcefile is c++ type, pls set USECPP=1
USECPP =
# For each target may need more than one source file, define TARGET 
# instead and add linking objects at OBJS
TARGET = timer
OBJS += main.o timer.o

# general makefile template
include ../GNU_makefile_template
