CCFLAGS = -W -Wall -I.. #-lm
# executable files for this directory
OBJECTS = mutiply.exe a+b.exe radixConvert.exe gcd.exe lcm.exe prime.exe \
	  factoring.exe division.exe
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
