# CFLAGS for users
#
CCFLAGS = -W -Wall
LOCFLAGS =

# For each one source file will generate one excutable xx.exe, you can 
# define multiple targetexe in TARGETEXE
TARGETEXE = hweight.exe
# USECPP = 1
# For each target may need more than one source file, define TARGET 
# instead and add linking objects at OBJS
TARGET = 
OBJS += 

# general makefile template
include ../GNU_makefile_template
