# CFLAGS for users
CCFLAGS = -W -Wall
LOCFLAGS =

# For each one source file will generate one excutable xx.exe, you can 
# define multiple targetexe in TARGETEXE
#TARGETEXE = testheap.exe

# For each target may need more than one source file, define TARGET 
# instead and add linking objects at OBJS
TARGET = shift.exe 
OBJS += shift.o

# general makefile template
include ../GNU_makefile_template
