CCFLAGS = -W -Wall -I..
# executable files for this directory
OBJECTS = median.exe palindromic.exe string.exe reverse.exe
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include GNU_makefile_template

$(OBJECTS) :
