# CFLAGS for users
#
CCFLAGS = -W -Wall -I../include
LOCFLAGS =
LDFLAGS =

# For each one source file will generate one excutable xx.exe, you can 
# define multiple target.exe in TARGETEXE
TARGETEXE = sudoku.exe
# If sourcefile is c++ type, pls set USECPP=1
USECPP = 1
# For each target may need more than one source file, define TARGET 
# instead and add linking objects at OBJS
TARGET = 
OBJS += 

# general makefile template
include ../GNU_makefile_template
