CCFLAGS = -W -Wall -I.. #-lm
# executable files for this directory
OBJECTS = iWannaGoHomeFloyd.exe iWannaGoHomeDijkstra.exe potentialFriends.exe \
	  wsCipher.exe logSort.exe cryption.exe isItATree.exe isItATree2.exe \
	  factor.exe medieval.exe rats.exe candySharing.exe bigIntegerFactor.exe \
	  mstFreckles.exe placeApple.exe bigDataRadixConvert.exe permutation.exe \
	  permutation2.exe falseCoin.exe skew.exe replaceWords.exe replaceWords2.exe \
	  binTree.exe eatCandy.exe jungleRoads.exe no7.exe rotateShift.exe \
	  counterfeitDollar.exe extremum.exe mileageBank.exe captain.exe repeater.exe \
	  oddPocket.exe oddPocket2.exe score.exe buyHouse.exe maxSubMatrix.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
