CCFLAGS = -W -Wall -I.. #-lm
# executable files for this directory
OBJECTS = iWannaGoHomeFloyd.exe iWannaGoHomeDijkstra.exe potentialFriends.exe \
	  wsCipher.exe logSort.exe cryption.exe isItATree.exe isItATree2.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
