# CFLAGS for users
#
#CCFLAGS = -W -Wall -I../include
CCFLAGS = -W -I../include
LOCFLAGS =
LDFLAGS =

# For each one source file will generate one excutable xx.exe, you can 
# define multiple targetexe in TARGETEXE
TARGETEXE = 
USECPP = 0
# For each target may need more than one source file, define TARGET 
# instead and add linking objects at OBJS
TARGET = scheduler
OBJS += main.o prio_hash.o sched.o simu_task.o

# general makefile template
include ../GNU_makefile_template
