CCFLAGS = -W -Wall -I..
# executable files for this directory
OBJECTS = maze.exe cocacola.exe primeRing.exe oilDeposit.exe templeOfBone.exe
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

$(OBJECTS) :
